.PHONY: clean All

All:
	@echo "----------Building project:[ fopen - Debug ]----------"
	@"$(MAKE)" -f  "fopen.mk"
clean:
	@echo "----------Cleaning project:[ fopen - Debug ]----------"
	@"$(MAKE)" -f  "fopen.mk" clean
