.PHONY: clean All

All:
	@echo "----------Building project:[ toydll - Debug ]----------"
	@"$(MAKE)" -f  "toydll.mk"
clean:
	@echo "----------Cleaning project:[ toydll - Debug ]----------"
	@"$(MAKE)" -f  "toydll.mk" clean
